# Generated by Django 3.1.7 on 2021-05-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='mim_note',
            new_name='min_note',
        ),
    ]
